name: Find FFTW
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: install
        run: sudo apt update && sudo apt install build-essential ninja-build cmake  # TODO dependencies # lcov
      - name: fftw-download # TODO: probably put in CMake
        run: |
          wget https://www.fftw.org/fftw-3.3.10.tar.gz && tar -xf fftw-3.3.10.tar.gz
      - name: configure-fftw-local
        working-directory: ./fftw-3.3.10
        run: |
          ./configure --prefix=`realpath ../fftw-install` && make && make install

      # remaining steps invoke CMake in various ways to test all installation pathways
      # they all run even if the previous ones fail
      - name: run CMake (local, with FFTW3_INCLUDE_DIR)
        run: |
          cmake -S . -B cmake-build-inc -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON -DFFTW3_INCLUDE_DIR=`realpath ./fftw-install/include`
          cmake --build cmake-build-inc
      - name: run CMake (local, with FFTW3_LIBRARY_DIR)
        if: '!cancelled()'
        run: |
          cmake -S . -B cmake-build-dir -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON -DFFTW3_LIBRARY_DIR=`realpath ./fftw-install/lib`
          cmake --build cmake-build-dir
      - name: run CMake (local, with FFTW3_LIBRARY)
        if: '!cancelled()'
        run: |
          cmake -S . -B cmake-build-lib -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON -DFFTW3_LIBRARY=`realpath ./fftw-install/lib/libfftw3.a`
          cmake --build cmake-build-lib
      - name: run CMake (local, with prefix path)
        if: '!cancelled()'
        run: |
          cmake -S . -B cmake-build-path -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON -DCMAKE_LIBRARY_PATH=`realpath ./fftw-install/lib` -DCMAKE_INCLUDE_PATH=`realpath ./fftw-install/include`
          cmake --build cmake-build-path
      - name: run CMake (local, with prefix path)
        if: '!cancelled()'
        run: |
          cmake -S . -B cmake-build-prefix -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON -DCMAKE_PREFIX_PATH=`realpath ./fftw-install`
          cmake --build cmake-build-prefix

      # global installation
      - name: configure-fftw-global
        working-directory: ./fftw-3.3.10
        if: '!cancelled()'
        run: |
          ./configure && make && sudo make install
      - name: run CMake (global)
        if: '!cancelled()'
        run: |
          cmake -S . -B cmake-build-global -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON
          cmake --build cmake-build-global

      # TODO probably not
      - name: run unit tests
        working-directory: ./cmake-build-global
        run: |
          ctest --verbose
