name: Ubuntu CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: install
        run: sudo apt update && sudo apt install build-essential ninja-build cmake  # TODO dependencies # lcov
      - name: fftw # TODO: probably put in CMake
        run: |
          wget https://www.fftw.org/fftw-3.3.10.tar.gz && tar -xf fftw-3.3.10.tar.gz && cd fftw-3.3.10 && ./configure --prefix=`realpath ../fftw-install` && make && make install
      - name: configure
        run: |
          cmake -S . -B cmake-build-debug -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFFTW_CPP_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-I./fftw-install/include" -DCMAKE_EXE_LINKER_FLAGS="-L./fftw-install/lib"
      - name: building
        run: |
          cmake --build cmake-build-debug
      - name: run unit tests
        working-directory: ./cmake-build-debug
        run: |
          ctest --verbose
